# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import judge_pb2 as judge__pb2


class JudgeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.judge = channel.unary_unary(
                '/JudgeService/judge',
                request_serializer=judge__pb2.SubmissionRequest.SerializeToString,
                response_deserializer=judge__pb2.SubmissionResult.FromString,
                )


class JudgeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def judge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JudgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'judge': grpc.unary_unary_rpc_method_handler(
                    servicer.judge,
                    request_deserializer=judge__pb2.SubmissionRequest.FromString,
                    response_serializer=judge__pb2.SubmissionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JudgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JudgeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def judge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JudgeService/judge',
            judge__pb2.SubmissionRequest.SerializeToString,
            judge__pb2.SubmissionResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
